import "@/app/ui/global.css"
import Navbar from "./ui/navbar";
import Footer from "./ui/footer";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SplashScreen from '@/app/ui/splashscreen';
import { ChakraProvider, Flex } from "@chakra-ui/react";
import { Box } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const GOOGLE_API_KEY = process.env.GOOGLE_MAPS_API;

  return (
    <html lang="en">
      <head>
        <script src={`https://maps.googleapis.com/maps/api/js?key=${GOOGLE_API_KEY}&libraries=places`}></script>
      </head>
      <body className={inter.className}>
        <ChakraProvider>
          <Navbar/>
          <Box pt={20} background={"#FAF9F6"}>
            {children}
          </Box>
          <Footer/>
        </ChakraProvider>
      </body>
    </html>
  );
}