import Footer from "@/app/ui/footer"
import Navbar from "@/app/ui/navbar"
import { Box, ChakraProvider } from "@chakra-ui/react"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <Navbar />
          <Box 
            background={"#FAF9F6"} 
            pt={100}
            display={"flex"}
            alignItems="center"
            justifyContent="center"
          >
            {children}
          </Box>
          <Footer/>
        </ChakraProvider>
      </body>
    </html>
  )
}
